cacheDir: ../wfexs-backend-test
crypt4gh:
  key: local_config.yaml.key
  passphrase: strive backyard dividing gumball
  pub: local_config.yaml.pub
agents:
  containerType: podman
  encrypted_fs:
    type: gocryptfs
  engineMode: local
  gitCommand: git
  javaCommand: java
  staticBashCommand: bash-linux-x86_64
workDir: ../wfexs-backend-test_WorkDir
